
package ticketlagbe;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class NowShowing extends javax.swing.JFrame {

    private String name;
    private String number;
    String tprice;

    public NowShowing(String name, String number) throws FileNotFoundException {
        initComponents();
        this.name = name;
        this.number = number;
               
        File file = new File("ShowNow.txt");
        File price = new File("TicketPrice.txt");
       
        Scanner sc = new Scanner(file);
	String [] cutter;
        String str = sc.nextLine();
        
        cutter = str.split(",");
        
        movie1.setText(cutter[0]);
        movie2.setText(cutter[1]);
        movie3.setText(cutter[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        viewButton2 = new javax.swing.JButton();
        viewButton3 = new javax.swing.JButton();
        viewButton1 = new javax.swing.JButton();
        movie1 = new javax.swing.JTextField();
        movie2 = new javax.swing.JTextField();
        movie3 = new javax.swing.JTextField();

        jTextField5.setText("jTextField5");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 102));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Now Showing");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        viewButton2.setBackground(new java.awt.Color(0, 0, 102));
        viewButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewButton2.setForeground(new java.awt.Color(255, 255, 255));
        viewButton2.setText("View Details");
        viewButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton2ActionPerformed(evt);
            }
        });

        viewButton3.setBackground(new java.awt.Color(0, 0, 102));
        viewButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewButton3.setForeground(new java.awt.Color(255, 255, 255));
        viewButton3.setText("View Details");
        viewButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton3ActionPerformed(evt);
            }
        });

        viewButton1.setBackground(new java.awt.Color(0, 0, 102));
        viewButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewButton1.setText("View Details");
        viewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(viewButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(viewButton2)
                .addGap(65, 65, 65)
                .addComponent(viewButton3)
                .addGap(30, 30, 30))
        );

        movie1.setEditable(false);
        movie1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        movie1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        movie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie1ActionPerformed(evt);
            }
        });

        movie2.setEditable(false);
        movie2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        movie2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        movie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie2ActionPerformed(evt);
            }
        });

        movie3.setEditable(false);
        movie3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        movie3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        movie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movie1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(movie2)
                    .addComponent(movie3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movie1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movie2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movie3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void movie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie1ActionPerformed
        // TODO add your handling code here:
        //movie1.setText(cutter[0]);
    }//GEN-LAST:event_movie1ActionPerformed
    
    private void viewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String movname = movie1.getText();
        File file = new File("TicketPrice.txt");
        try {
            Scanner sc = new Scanner(file);
            String str = sc.nextLine();
            String [] cutter;
            cutter = str.split(",");
            tprice = cutter[0];
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new BookTicket(name, movname, number, tprice).setVisible(true);
    }//GEN-LAST:event_viewButton1ActionPerformed

    private void viewButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String movname = movie2.getText();
        File file = new File("TicketPrice.txt");
        try {
            Scanner sc = new Scanner(file);
            String str = sc.nextLine();
            String [] cutter;
            cutter = str.split(",");
            tprice = cutter[1];
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new BookTicket(name, movname, number, tprice).setVisible(true);
    }//GEN-LAST:event_viewButton2ActionPerformed

    private void viewButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String movname = movie3.getText();
        File file = new File("TicketPrice.txt");
        try {
            Scanner sc = new Scanner(file);
            String str = sc.nextLine();
            String [] cutter;
            cutter = str.split(",");
            tprice = cutter[2];
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new BookTicket(name, movname, number, tprice).setVisible(true);
    }//GEN-LAST:event_viewButton3ActionPerformed

    private void movie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie2ActionPerformed

    private void movie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NowShowing(String name).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField movie1;
    private javax.swing.JTextField movie2;
    private javax.swing.JTextField movie3;
    private javax.swing.JButton viewButton1;
    private javax.swing.JButton viewButton2;
    private javax.swing.JButton viewButton3;
    // End of variables declaration//GEN-END:variables
}
